#!/usr/bin/env python

import rospy
from rosgraph_monitor.monitor_manager import MonitorManager, ServiceWrapper

from ros_graph_parser.srv import Scan
from diagnostic_msgs.msg import DiagnosticArray, DiagnosticStatus


class GraphScanService(ServiceWrapper):
    def __init__(self):
        super(GraphScanService, self).__init__('scan_ros_graph', Scan)

    # This function needs to be implemented by every service wrapper
    # extract diagnostics from response here
    def diagnostics_from_response(self, resp):
        # print(resp)

        self.compare_with_model(resp)

        status_msg = DiagnosticStatus()
        status_msg.level = DiagnosticStatus.OK
        status_msg.name = "ROS Graph"
        status_msg.message = "alive"

        return status_msg

    # compare with ros model here
    def compare_with_model(self, resp):
        # how to extract the model from the string?
        pass


if __name__ == "__main__":
    rospy.init_node('graph_monitor')
    manager = MonitorManager()

    # how can this be read from a YAML file
    # ideally should have service name and type only
    graph_service = GraphScanService()
    manager.register_service(graph_service)

    manager.loop()
    rospy.spin()
